language: cpp
dist: xenial
before_script:
- sudo apt-add-repository -y "deb http://archive.ubuntu.com/ubuntu xenial main universe"
- sudo apt-get install -y libgtest-dev build-essential cmake
- pushd /usr/src/gtest
- sudo cmake .
- sudo cmake --build . -- -j "`nproc`"
- sudo cp *.a /usr/lib
- popd
script:
- cmake -D BUILD_TYPE_RELEASE=ON .
- cmake --build . -- -j "`nproc`"
- cmake --build . --target test -- -j "`nproc`"
- cmake --build . --target package -- -j "`nproc`"
deploy:
  provider: script
  skip_cleanup: true
  debug: on
  script: bash .deploy.sh "$TRAVIS_BUILD_NUMBER" "$BINTRAY_API_KEY"
  on:
    branch: master
